version: "2.1"

volumes:
  dashboard-data:
  sense-data: {}

services:
  dashboard:
    image: balenablocks/dashboard
    build: ./
    restart: always
    volumes:
      - "dashboard-data:/data"
    ports:
      - "80"
